version: '3.8'

services:
  db:
    image: postgres:16
    container_name: projects
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projects
    ports:
      - "5432:5432"
    volumes:
      - projects:/var/lib/postgresql/data

volumes:
  projects: